"""Integration tests for placo IK and the pyrender render path.

These need the fetched URDF (scripts/fetch_urdf.sh), placo, pyrender + an offscreen GL
backend (OSMesa/EGL). They skip cleanly when any of those is missing.
"""

import os

import numpy as np
import pytest

os.environ.setdefault("PYOPENGL_PLATFORM", "osmesa")

from egodex_robot import geometry  # noqa: E402
from egodex_robot.ik import DEFAULT_URDF  # noqa: E402

placo = pytest.importorskip("placo")
pyrender = pytest.importorskip("pyrender")
pytest.importorskip("trimesh")

if not DEFAULT_URDF.exists():
    pytest.skip("Mobile ALOHA URDF not fetched; run scripts/fetch_urdf.sh", allow_module_level=True)


@pytest.fixture(scope="module")
def ik():
    from egodex_robot.ik import RobotIK

    return RobotIK()


def test_reachable_pose_converges_both_position_and_orientation(ik):
    """A pose generated by FK from in-limit joints must be reached in position AND orientation."""
    robot = ik.robot
    robot.reset()
    robot.set_T_world_fbase(np.eye(4))
    for j, v in [
        ("fl_joint1", 0.4), ("fl_joint2", 0.6), ("fl_joint3", -0.5),
        ("fl_joint4", 0.3), ("fl_joint5", -0.4), ("fl_joint6", 0.2),
    ]:
        robot.set_joint(j, v)
    robot.update_kinematics()
    target = np.asarray(robot.get_T_world_frame("fl_link6"), dtype=float).copy()

    result = ik.solve({"left": target}, base_transform=np.eye(4))
    arm = result.arms["left"]
    assert arm.position_residual < 1e-2
    assert arm.orientation_residual < np.deg2rad(2.0)
    assert arm.reachable


def test_solve_returns_all_link_transforms(ik):
    result = ik.solve({}, base_transform=np.eye(4), max_iters=1)
    assert "fl_link6" in result.link_transforms
    assert "fr_link6" in result.link_transforms
    for T in result.link_transforms.values():
        assert T.shape == (4, 4)


def test_unreachable_target_is_flagged(ik):
    # 5 m away is well outside the workspace -> not reachable, but no exception.
    far = geometry.make_se3(np.eye(3), [5.0, 5.0, 5.0])
    result = ik.solve({"left": far}, base_transform=np.eye(4))
    assert not result.arms["left"].reachable
    assert result.arms["left"].position_residual > 0.1


def test_render_produces_foreground_rgba(ik):
    from egodex_robot.stages import render as render_stage

    result = ik.solve({}, base_transform=np.eye(4), max_iters=1)
    K = np.array([[600.0, 0, 320], [0, 600.0, 240], [0, 0, 1]])
    T_world_cam = geometry.make_se3(np.eye(3), [0.0, 0.3, 3.0])  # in front, looking -z
    rgba = render_stage.render_robot(result.link_transforms, K, T_world_cam, (640, 480))
    assert rgba.shape == (480, 640, 4)
    assert rgba.dtype == np.uint8
    assert (rgba[..., 3] > 0).sum() > 1000  # the robot occupies a meaningful area
